### PR TITLE
Create need it app

### PR DESCRIPTION
**Pull request by HugoLencastre**

### CODE REVIEW

**Comment by bsweets** [comment]
Thanks for submitting this, but we do not accept pull requests against the ServiceNow training master repository. If you want to access your specific work from a learning module, we recommend that you do not merge the changes into the master branch. If you still want to merge, please select **your fork** as the *base repository* in GitHub before making the pull request.

**Comment by HugoLencastre** [comment]
Sorry, I just notice what I did after, I tried to reverse the request but I
couldn't do it.

Sorry again

A segunda, 20/07/2020, 16:48, Ben Sweetser <notifications@github.com>
escreveu:

**Comment by bsweets** [comment]
No worries. It is really easy to miss that the pull request is created against the original repository.

Happy developing!
Ben

**Comment by HugoLencastre** [comment]
Thanks for the understanding

Good work, bye

A segunda, 20/07/2020, 16:52, Ben Sweetser <notifications@github.com>
escreveu:

**Pull request closed without merging**
